name: .NET Core

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 2.2.108
    - name: Package and publish with dotnet
      run: |
        cd src/
        dotnet restore
        dotnet pack --configuration Release
        dotnet nuget push "$GITHUB_WORKSPACE/src/GithubPackageTest/bin/Release/GithubPackageTest.*.nupkg" --source "github" --api-key ${{ secrets.GITHUB_TOKEN }}
