name: .NET Core

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 2.2.108
    - name: Nuget Restore
      run: dotnet restore src/
    - name: Package
      run: dotnet pack src/ --configuration Release
    - name: Publish
      run: dotnet nuget push "$GITHUB_WORKSPACE/src/GithubPackageTest/bin/Release/GithubPackageTest.*.nupkg" --source "github" --api-key ${{ secrets.GITHUB_TOKEN }}
